Add information of the library usage and example project. Closes #25
vulcancreative/serverless-storage pull request #26
Opened 2022-04-24 01:44 UTC by ffebriansyah

Fixes #25 

Add information of the library usage and example project.

2022-04-24 19:50 UTC, chris-calo requested changes
@ffebriansyah great start, thanks again for helping with this! Maybe someday soon people aside from us can use it with this! 🙂

I left a little bit of feedback, and may see if we can't get a project logo added in here!

2022-04-24 19:50 UTC, chris-calo commented on README.md
> +S3 to store files.
Suggestion to edit:

> Serverless storage is key value storage, using DynamoDB as the backend for data storing, and
S3 to store files.

> `serverlessStorage` is a backend key/value library (similar to `localStorage` or `sessionStorage`), which uses a combination of DynamoDB and S3 to store data blobs, greatly simplifying database connectivity in a serverless environment.

2022-04-24 19:50 UTC, chris-calo commented on README.md
> +## Usage
Suggestion to edit:

> `## Usage`

> `## Basic Use`

2022-04-24 19:50 UTC, chris-calo commented on README.md
> +
@ffebriansyah we should probably have a section here called `Configuration`

2022-04-24 19:50 UTC, chris-calo commented on README.md
> +
@ffebriansyah we should probably have a section here called `Installation`, just showing the `npm`/`yarn` commands necessary to install

2022-04-25 01:47 UTC, ffebriansyah commented on README.md
> +Example implementation for this project can be found [here](https://github.com/vulcancreative/serverless-storage-test)
@chris-calo with this one here, do you think the example project should be moved to an `example` folder in `serverless-storage` folder, or should we just make `serverless-storage-test` a public, or keep it as is for now (private)?

2022-04-25 02:24 UTC, chris-calo commented on README.md
> +Example implementation for this project can be found [here](https://github.com/vulcancreative/serverless-storage-test)
@ffebriansyah certainly wouldn't hurt, if you have time and it can be safely isolated! I would just make sure it doesn't get packed into the NPM build, if possible

2022-04-25 02:28 UTC, ffebriansyah commented
@chris-calo by the project logo you mentioned above, do we have a serverless-storage logo somewhere?

2022-04-25 02:39 UTC, chris-calo commented
> @chris-calo by the project logo you mentioned above, do we have a serverless-storage logo somewhere?

No, nothing yet. I'll have to make one to somehow slot into the Serverless ecosystem. I think I have a template for the one I made for Framework kicking around somewhere. Will see if I can't dig it up 👍

2022-04-25 06:39 UTC, ffebriansyah commented on README.md
> +Example implementation for this project can be found [here](https://github.com/vulcancreative/serverless-storage-test)
Added a folder `example`

2022-04-25 06:46 UTC, ffebriansyah commented
@chris-calo I've added the requested changes.

2022-04-26 06:06 UTC, chris-calo approved these changes

2022-04-26 06:10 UTC, merged